### ISSUE TITLE
Persistent Cloud Anchors - ErrorNotAuthorized

### ISSUE THREAD

**Issue by JosquinDpt** [google-ar/arcore-unity-extensions#22]
Testing with AR Foundation on Android:

Unity 2019.4.11f1
AR Foundation 4.1.0 Preview 9
ARCore Extensions 1.20

Running the sample scene, everything is going well until the CreateCloudAnchor is triggered:
Host Failed
Failed to host a Cloud Anchorwith error 
Error Not Authorized

I'm running it with the keyless setting.

**Comment by JosquinDpt** [comment]
Contrary to what it is written in the Project Settings, KeyLess is not the recommended option and will not work.
![image](https://user-images.githubusercontent.com/29232088/95491946-5d35fc80-0968-11eb-9347-42fdef5705ec.png)
![image](https://user-images.githubusercontent.com/29232088/95491971-67f09180-0968-11eb-9249-33275f8eee01.png)

Using an API fixed the issue.

**Comment by JosquinDpt** [comment]
In Google Cloud Platform:
- OAuth 2.0 Client IDs is setup with the package name and a certificate fingerprint
- A consent screen is setup with 
![image](https://user-images.githubusercontent.com/29232088/95998817-3ca3f180-0e03-11eb-8a44-0aa8a8212d50.png)

In Unity, keyless is selected, no API key is set.

When I start the app I don't see any consent screen, is is normal?
After placing an Anchor it's still: Error Not Authorized

**Comment by michelepanegrossi** [comment]
I am also trying to get this to work. I have followed the instructions for [Keyless authentication](https://developers.google.com/ar/develop/unity/cloud-anchors/developer-guide-android) but I keep getting the same Error Not Authorized.

Is this really not available yet or am I doing anything wrong?

**Comment by JosquinDpt** [comment]
@tedruxpin 
Any chance to have more details on this issue?
The documentation seems to be lacking something, or it's because of all the preview packages and new Unity version we are using that just doesn't work. Is there a project setup somewhere with the right packages, Gradle version (I'm not talking about the sample)?
Thanks

**Comment by elCangrejo** [comment]
I had the same problem with the authorization. After updating the project to 2020.2.0b11 it seems to be working. I can host and resolve a persistent anchor, with keyless method. 

I was running 2020.1.10 before, which had the ErrorNotAuthorized issues. The major difference between these editor versions is the updated Gradle version integrated in 2020.2, the older version needed to install the Gradle 5.6.4 (that is required for the Arcore Extensions to work) manually, so maybe the problem lies somewhere there

**Comment by MarcinSkierskiTS** [comment]
elCangrejo solution working on Android but the ErrorNotAuthorized issue also occures on IOS although TOKEN is generated on separate server and set using 'ARAnchorManager.SetAuthToken(string authToken)' on Unity side. 

UNITY CODE
[UnityTokenGenerator.txt](https://github.com/google-ar/arcore-unity-extensions/files/5926220/UnityTokenGenerator.txt)
SERVER SIDE CODE
[ServerTokenGenerator.txt](https://github.com/google-ar/arcore-unity-extensions/files/5926221/ServerTokenGenerator.txt)

**Comment by hcnw** [comment]
> I had the same problem with the authorization. After updating the project to 2020.2.0b11 it seems to be working. I can host and resolve a persistent anchor, with keyless method.
> 
> I was running 2020.1.10 before, which had the ErrorNotAuthorized issues. The major difference between these editor versions is the updated Gradle version integrated in 2020.2, the older version needed to install the Gradle 5.6.4 (that is required for the Arcore Extensions to work) manually, so maybe the problem lies somewhere there

@elCangrejo Can you please explain more about how you handled gradle version? Any changes you made or it is just Unity version update that did the magic?
I tried with new Unity version but still the same authorization issue!

Thanks,

**Comment by elCangrejo** [comment]
@hcnw So if you are running 2020.1 or below you can download the Gradle version 5.6.4. on this [website](https://gradle.org/releases/). You install it and then you can set it as Gradle Path in your Unity Preferences under External Tools.

At the moment I'm using version 2020.2.1 and I didn't have any problems with this specific error. So if the Gradle is not working, maybe consider upgrading to the newest version. If that is also not working, then it is probably time to pray to the Unity gods

**Comment by cloudnp** [comment]
@elCangrejo
What you're talking about is a one-day anchor? Or do you mean Persistent Anchor?

**Comment by elCangrejo** [comment]
> 
> 
> @elCangrejo
> What you're talking about is a one-day anchor? Or do you mean Persistent Anchor?


I'm talking only about the persistent Anchors with keyless method.

**Comment by kshitizsv-vizara** [comment]
for me,

> @hcnw So if you are running 2020.1 or below you can download the Gradle version 5.6.4. on this [website](https://gradle.org/releases/). You install it and then you can set it as Gradle Path in your Unity Preferences under External Tools.
> 
> At the moment I'm using version 2020.2.1 and I didn't have any problems with this specific error. So if the Gradle is not working, maybe consider upgrading to the newest version. If that is also not working, then it is probably time to pray to the Unity gods

For me, i am able to host an anchor but it can only  be resolved in the device that hosted it. If i try to resolve it in another device, failed to resolve: not authorized error comes. is there any way to resolve it in another device ?

**Comment by kshitizsv-vizara** [comment]
Got is working Guys.
Try using:
- unity version 2020.2.6f1
- Gradle Version 6.8.3
- Android Extension version 1.23

**Comment by iAmJuan550** [comment]
How did you update your gradle version in Unity3d?

**Comment by iAmJuan550** [comment]
@kshitizsv-vizara provide a step by step solution. How did you set the gradle version? How did you set the Android Extension version? Your comment is quite vague

**Comment by iAmJuan550** [comment]
The solutions offered here no longer work. I have tried running the Persistent cloud anchor sample app and I still can't host anchors.

**Comment by devbridie** [comment]
I can't seem to reproduce this problem; here are the steps I followed:

1. Get the persistent cloud anchor sample app to work by following various instructions on [the quickstart](https://developers.google.com/ar/develop/unity/quickstart-android) and [build for Android 11](https://developers.google.com/ar/develop/unity/android-11-build).
2. Verified that the project does NOT work, as I did not configure any Google Cloud Platform settings.
3. In a new GCP project, I created a OAuth 2.0 client ID (and configured an OAuth consent screen), using package name from **Player Settings > Android > Other Settings >  Package Name** and SHA values from `keytool -keystore ~/.android/debug.keystore -list -v`.
4. Enabled the [ARCore Cloud Anchor API in GCP](https://console.cloud.google.com/apis/library/arcorecloudanchor.googleapis.com).
5. Rebuilt and ran the Persistent Cloud Anchor sample app. This time, I was able to host an anchor.

I'm also using gradle-6.8.3, but I don't think that should matter (posting just in case)

Here are some troubleshooting steps; try them out and ensure that the values in your Google Cloud project match:

1. Check the SHA-1 key used to sign your apk and ensure it's the same as the key in GCP: `Android/sdk/build-tools/30.0.1/apksigner verify --print-certs built-unity-game.apk`
2. Use `aapt` to confirm the package name of your built apk and ensure it's the same as the package name in GCP: `Android/sdk/build-tools/30.0.1/aapt dump badging built-unity-game.apk | grep package:`

**Comment by iAmJuan550** [comment]
@devbridie I followed your instruction but now I can't even find the option for keyless cloud anchor hosting. Why are the Unity tutorials so fragmented for ArFoundtion? Please provide a step-by-step guide as to what I should do.

**Comment by devbridie** [comment]
Keyless documentation is located [here](https://developers.google.com/ar/develop/unity-arf/cloud-anchors/developer-guide-android#keyless-authentication)!

**Comment by iAmJuan550** [comment]
huh? Of course I know about that. I tried that, it doesn't work. I still get the Error Not Authrized message.

**Comment by iAmJuan550** [comment]
Any update on this? Either offer a solution or tell us that is not working so we may stop wasting our time. There is no one to message in Google to make this work as well. You need to fix your customer service for cloud anchors

**Comment by ChristianSchnellmann** [comment]
We can't get keyless authentication to work either. Any update on this would be appreciated.

**Comment by hcnw** [comment]
After trying multiple times, realized this is intentional

**Comment by iAmJuan550** [comment]
@hcnw how do you know this is intentional?

**Comment by hcnw** [comment]
I do not know exact but I think it should have worked for someone by now if
it was functional.
Also, there is no resolution to this so far

**Comment by elCangrejo** [comment]
Since I ran into trouble with my team again, regarding the persistent Anchor creation, I can share some tips:
- Run the newest Unity Version possible (2020.3.1 is working fine for me)
- Try Assets> External Dependency Manager > Android Resolver > Force Resolve
- Be patient!!! For my Team it took a day, after adding the keystore SHA to the Google Developer Console, until the Hosting & Resolving was working without troubles

**Comment by Saicopate** [comment]
For those fighting with ErrorNotAuthorized problem - check your if your androidresolverdependencies.xml file contains the following references:
  <files>
    <file>Assets/Plugins/Android/android.arch.core.common-1.0.0.jar</file>
    <file>Assets/Plugins/Android/android.arch.lifecycle.common-1.0.0.jar</file>
    <file>Assets/Plugins/Android/android.arch.lifecycle.runtime-1.0.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-annotations-26.1.0.jar</file>
    <file>Assets/Plugins/Android/com.android.support.support-compat-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-core-ui-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-core-utils-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-fragment-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-media-compat-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-v4-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-auth-base-16.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-base-16.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-basement-16.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-tasks-16.0.1.aar</file>
  </files>

It took me a lot o time to point down the cause of this error.

**Comment by Renkon117** [comment]
Anyone having trouble building on iOS platform? How do I build iOS app with Authentication Token?
<img width="856" alt="スクリーンショット 2021-07-13 19 33 06" src="https://user-images.githubusercontent.com/47985882/125437546-6a7e1731-dc6f-48f9-b61b-a3e761a55f29.png">

**Comment by devbridie** [comment]
@Renkon117, please see instructions on the [Cloud Anchors developer guide for iOS](https://developers.devsite.corp.google.com/ar/develop/unity-arf/cloud-anchors/developer-guide-ios#token-authentication) for how to use SetAuthToken at runtime.

As mentioned [on the other thread](https://github.com/google-ar/arcore-unity-extensions/issues/48#issuecomment-875646209), we've identified a problem with Unity's package cache isolation and are working towards a fix. In the meantime, here are some troubleshooting steps from that thread:
 
> 1. Check for the existence of `ProjectSettings/AndroidResolverDependencies.xml`. If this **does not** exist, then probably this is the source of problems;
> 2. Check `Temp/gradleOut/unityLibrary/build.gradle`; this should contain some lines with `'com.google.android.gms`.
> 
> If this is the case, then GMS authentication libraries are missing at runtime, and this causes authentication to fail. 
> 
> This may be caused by incorrect permissions in our provided tgz. If you're encountering this, a possible workaround is to **remove ARCore Extensions** from the Package Manager, then extracting the tgz first, then use `Import from Disk` to import the resulting `package.json`. Trigger a new build, and (1) and (2) should appear from above.

**Comment by sam1am** [comment]
I have run into this error many times and for many reasons. The latest was solved by deleting ProjectSettings/AndroidResolverDependencies.xml and letting Unity regenerate it.

**Comment by iAmJuan550** [comment]
I solved the problem by importing the ARCore extensions from the package manager

**Comment by Dweeh** [comment]
Got the same problem.
Can I have missed something in the Google Cloud settings?
Should I have added any scopes in the OATH consent screen setup or something?
I could not find any scope that seemed to fit...

**Comment by rc1** [comment]
Worth noting you need to enable the API in the console: https://console.cloud.google.com/apis/library/arcore

**Comment by TimmyBest** [comment]
ttl = 365 strikes back

ARCore Extensions Version 1.37.0
Unity 2021.3.16
ErrorNotAuthorized -- after updating to the new API.


Old API  worked perfectly. 
Token is verified and valid,

API key -> works great

Nothing from above worked for us.

This is the 3rd time this project breaks due to ARCloudAnchor API update.

@devbridie Please help us! Again 😔

**Comment by hlefe** [comment]
> ttl = 365 strikes back
> 
> ARCore Extensions Version 1.37.0 Unity 2021.3.16 ErrorNotAuthorized -- after updating to the new API.
> 
> Old API worked perfectly. Token is verified and valid,
> 
> API key -> works great
> 
> Nothing from above worked for us.
> 
> This is the 3rd time this project breaks due to ARCloudAnchor API update.
> 
> @devbridie Please help us! Again 😔

Hello everyone,

I'm not developing with Unity but rather with Flutter, and I too encountered the ErrorNotAuthorized issue while working with cloud anchors (using the plugin ar_flutter_plugin_flutterflow: ^0.7.41). The discussions in this thread have been immensely helpful in guiding me towards a resolution. I'd like to contribute back by sharing a couple of things that resolved my issue, which might help others in the future:

Upgrade AR Core to version 1.33 in build.gradle:
I changed my implementation to "com.google.ar:core:1.33.0" because it seems that cloud anchors no longer function with previous versions, leading to the ErrorNotAuthorized error. This upgrade was a crucial step in resolving the issue. It's also essential to ensure that the ARCore API is enabled, as the ARCore Cloud Anchor API relies on it. More information can be found here: [ARCore Cloud Anchors Endpoint Changes](https://developers.google.com/ar/develop/cloud-anchors/endpoint-changes?hl=en).
Disabling Minification in Release Mode:
After making the above changes, the ErrorNotAuthorized disappeared in the debug mode, but it reappeared upon switching to release mode. To address this, I disabled code shrinking and minification by adding the following lines to my app/build.gradle:
gradle
Copy code
buildTypes {
    release {
        minifyEnabled false
        shrinkResources false
    }
}
This step ensured that the release version of my app worked without triggering the ErrorNotAuthorized error.
I hope this helps anyone facing the same issue. It's always a bit tricky navigating these errors, but with a community sharing insights and solutions, it becomes much more manageable.

**Comment by LexDeKogel** [comment]
I never had this issue before but after updating the In App Purchasing package (which is required by google) I get this every time on Android.

I am lost, I tried updating AR core, I tried updating Unity, I tried disabling minification. Nothing seems to work and I don't understand why. Nothing else seems to be effected by updating that package, just this. Anyone have any ideas on what I can try next? I'm on Unity 2021.3.43f1
